export {default as Card} from "./Card/Card"
export{default as MainCointainer} from "../screens/main"
export {default as Nav} from "./nav/nav"
export {default as Comments} from "./Comments/comments"
export {default as Profile} from "./Profileinfo/Profileinfo"
